"""Initial migration

Revision ID: 00339a73c7b9
Revises: 
Create Date: 2026-07-05 13:37:19.459349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00339a73c7b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breeds',
    sa.Column('breed_id', sa.Integer(), nullable=False),
    sa.Column('breed_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('breed_id'),
    sa.UniqueConstraint('breed_name')
    )
    op.create_table('users',
    sa.Column('usr_id', sa.Integer(), nullable=False),
    sa.Column('usr_email', sa.String(length=255), nullable=False),
    sa.Column('usr_password_hash', sa.String(length=255), nullable=False),
    sa.Column('usr_join_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('usr_id'),
    sa.UniqueConstraint('usr_email')
    )
    op.create_table('disciplines',
    sa.Column('disc_id', sa.Integer(), nullable=False),
    sa.Column('disc_name', sa.String(length=100), nullable=False),
    sa.Column('disc_type', sa.Integer(), nullable=False),
    sa.Column('disc_usr_id', sa.Integer(), nullable=True),
    sa.Column('disc_active', sa.Integer(), nullable=False),
    sa.CheckConstraint('disc_active IN (0, 1)', name='check_disc_active'),
    sa.CheckConstraint('disc_type IN (0, 1)', name='check_disc_type'),
    sa.ForeignKeyConstraint(['disc_usr_id'], ['users.usr_id'], ),
    sa.PrimaryKeyConstraint('disc_id')
    )
    op.create_table('dogs',
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('dog_name_full', sa.String(length=250), nullable=False),
    sa.Column('dog_name_short', sa.String(length=100), nullable=False),
    sa.Column('dog_usr_id', sa.Integer(), nullable=False),
    sa.Column('dog_breed_id', sa.Integer(), nullable=True),
    sa.Column('dog_birth_date', sa.Date(), nullable=True),
    sa.Column('dog_note', sa.Text(), nullable=True),
    sa.Column('dog_active', sa.Integer(), nullable=False),
    sa.CheckConstraint('dog_active IN (0, 1)', name='check_dog_active'),
    sa.ForeignKeyConstraint(['dog_breed_id'], ['breeds.breed_id'], ),
    sa.ForeignKeyConstraint(['dog_usr_id'], ['users.usr_id'], ),
    sa.PrimaryKeyConstraint('dog_id')
    )
    op.create_table('workout_groups',
    sa.Column('wgroup_id', sa.Integer(), nullable=False),
    sa.Column('wgroup_usr_id', sa.Integer(), nullable=False),
    sa.Column('wgroup_creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wgroup_usr_id'], ['users.usr_id'], ),
    sa.PrimaryKeyConstraint('wgroup_id')
    )
    op.create_table('workouts',
    sa.Column('wout_id', sa.Integer(), nullable=False),
    sa.Column('wout_start_datetime', sa.DateTime(), nullable=False),
    sa.Column('wout_end_datetime', sa.DateTime(), nullable=False),
    sa.Column('wout_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('wout_disc_id', sa.Integer(), nullable=False),
    sa.Column('wout_usr_id', sa.Integer(), nullable=False),
    sa.Column('wout_dog_id', sa.Integer(), nullable=False),
    sa.Column('wout_focus', sa.Text(), nullable=True),
    sa.Column('wout_status', sa.Integer(), nullable=False),
    sa.Column('wout_score', sa.String(length=100), nullable=True),
    sa.Column('wout_note', sa.Text(), nullable=True),
    sa.Column('wout_creation_date', sa.DateTime(), nullable=False),
    sa.Column('wout_wgroup_id', sa.Integer(), nullable=True),
    sa.Column('wout_active', sa.Integer(), nullable=False),
    sa.CheckConstraint('wout_active IN (0, 1)', name='check_wout_active'),
    sa.CheckConstraint('wout_duration_minutes >= 0', name='check_wout_duration_positive'),
    sa.CheckConstraint('wout_status IN (0, 1, 2)', name='check_wout_status'),
    sa.ForeignKeyConstraint(['wout_disc_id'], ['disciplines.disc_id'], ),
    sa.ForeignKeyConstraint(['wout_dog_id'], ['dogs.dog_id'], ),
    sa.ForeignKeyConstraint(['wout_usr_id'], ['users.usr_id'], ),
    sa.ForeignKeyConstraint(['wout_wgroup_id'], ['workout_groups.wgroup_id'], ),
    sa.PrimaryKeyConstraint('wout_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workouts')
    op.drop_table('workout_groups')
    op.drop_table('dogs')
    op.drop_table('disciplines')
    op.drop_table('users')
    op.drop_table('breeds')
    # ### end Alembic commands ###
